modLoader = "javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion = "[40,)" #mandatory
license = "MIT License"
# A URL to refer people to when problems occur with this mod
issueTrackerURL = "https://github.com/BONNePlayground/VaultHuntersDiscordIntegrator/issues" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId = "vhdiscord" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version = "${file.jarVersion}" #mandatory
# A display name for the mod
displayName = "Vault Hunters Discord Integration" #mandatory
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL = "" #optional
# A text field displayed in the mod UI
authors = "BONNe" #optional
# The description text for the mod (multi line!) (#mandatory)
description = '''
This mod adds Vault Hunters integration in your favorite discord bot mod.
'''
[[dependencies.vhdiscord]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2]"
ordering = "NONE"
side = "SERVER"
[[dependencies.vhdiscord]]
modId = "forge"
mandatory = true
versionRange = "[40.1.0,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.vhdiscord]]
modId = "the_vault"
mandatory = true
ordering = "AFTER"
versionRange = "[1.18.2-3.8.0.1681,)"
side = "SERVER"
[[dependencies.vhdiscord]]
modId = "dcintegration"
mandatory = false
versionRange = "[2.5.0,)"
ordering = "AFTER"
side = "SERVER"
[[dependencies.vhdiscord]]
modId = "mc2discord"
mandatory = false
versionRange = "[3.3.0,)"
ordering = "AFTER"
side = "SERVER"
